version: '3.8'

services:
  proxy-reverso:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html/
  app1:
    image: evertonagilar/webpage-blue:1.0.0
#    ports:
#      - 8081:8080

  app2:
    image: evertonagilar/webpage-green:1.0.0
#    ports:
#      - 8082:8080




